PS1='[\w]$ '
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
alias grep='grep -i --color'
alias ls='ls --color=auto'
alias ll='ls -lavh --ignore=..'
alias l='ls -lavh --ignore=.?*'
alias u='sudo pacman -Syyu'
alias c='sudo pacman -Scc'
alias i='sudo pacman -Sy $1'
alias r='sudo pacman -Rs $1'
